<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AgentSeeder extends Seeder
{
    public function run(): void
    {
        $agents = [
            [
                'user_id' => null,
                'nama' => 'Azel Khoirunisa',
                'nib' => '1234567890123',
                'alamat' => 'Jl. Thamrin No. 10, Jakarta Pusat',
                'foto_profile' => 'https://www.shutterstock.com/image-photo/confident-smiling-asian-woman-wearing-600w-2453306259.jpg', // Gambar HD untuk profil
                'nama_perusahaan' => 'Properti Jaya Abadi',
                'email' => 'budi.setiawan@pja.com',
                'telepon' => '081123456789',
                'foto' => 'https://www.shutterstock.com/image-photo/confident-smiling-asian-woman-wearing-600w-2453306259.jpg', // Gambar HD untuk perusahaan/lainnya
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Citra Dewi',
                'nib' => '9876543210987',
                'alamat' => 'Jl. Asia Afrika No. 20, Bandung',
                'foto_profile' => 'https://www.shutterstock.com/image-photo/overjoyed-young-asian-woman-red-600w-2494227259.jpg',
                'nama_perusahaan' => 'Rumah Impian Developer',
                'email' => 'citra.dewi@rid.com',
                'telepon' => '082234567890',
                'foto' => 'https://www.shutterstock.com/image-photo/overjoyed-young-asian-woman-red-600w-2494227259.jpg',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Sinta Kusuma',
                'nib' => '1122334455667',
                'alamat' => 'Jl. Gajah Mada No. 30, Semarang',
                'foto_profile' => 'https://www.shutterstock.com/image-photo/portrait-happy-young-asian-muslim-600w-2526398889.jpg',
                'nama_perusahaan' => 'Investasi Properti Unggul',
                'email' => 'dian.kusuma@ipu.com',
                'telepon' => '083345678901',
                'foto' => 'https://www.shutterstock.com/image-photo/portrait-happy-young-asian-muslim-600w-2526398889.jpg',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Dian Larasati',
                'nib' => '4455667788990',
                'alamat' => 'Jl. Diponegoro No. 40, Surabaya',
                'foto_profile' => 'https://www.shutterstock.com/image-photo/surprised-asian-woman-reclines-on-260nw-2180834637.jpg',
                'nama_perusahaan' => 'Surabaya Realty',
                'email' => 'eko.prasetyo@sr.com',
                'telepon' => '085567890123',
                'foto' => 'https://www.shutterstock.com/image-photo/surprised-asian-woman-reclines-on-260nw-2180834637.jpg',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Fina Amelia',
                'nib' => '7788990011223',
                'alamat' => 'Jl. Sudirman No. 50, Medan',
                'foto_profile' => 'https://i.pravatar.cc/150?img=5',
                'nama_perusahaan' => 'Medan Property Agent',
                'email' => 'fina.amelia@mpa.com',
                'telepon' => '087789012345',
                'foto' => 'https://picsum.photos/800/600?random=5',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Gita Novita',
                'nib' => '2233445566778',
                'alamat' => 'Jl. HR Rasuna Said No. 60, Jakarta Selatan',
                'foto_profile' => 'https://i.pravatar.cc/150?img=6',
                'nama_perusahaan' => 'Mega Properti Indonesia',
                'email' => 'gita.novita@mpi.com',
                'telepon' => '089901234567',
                'foto' => 'https://picsum.photos/800/600?random=6',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Hadi Wibowo',
                'nib' => '5566778899001',
                'alamat' => 'Jl. Hayam Wuruk No. 70, Denpasar, Bali',
                'foto_profile' => 'https://i.pravatar.cc/150?img=7',
                'nama_perusahaan' => 'Bali Home Specialist',
                'email' => 'hadi.wibowo@bhs.com',
                'telepon' => '081210987654',
                'foto' => 'https://picsum.photos/800/600?random=7',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Indra Wijaya',
                'nib' => '8899001122334',
                'alamat' => 'Jl. Veteran No. 80, Yogyakarta',
                'foto_profile' => 'https://i.pravatar.cc/150?img=8',
                'nama_perusahaan' => 'Yogya Properti Eksklusif',
                'email' => 'indra.wijaya@ype.com',
                'telepon' => '082321098765',
                'foto' => 'https://picsum.photos/800/600?random=8',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Joko Santoso',
                'nib' => '1011223344556',
                'alamat' => 'Jl. Ahmad Yani No. 90, Makassar',
                'foto_profile' => 'https://i.pravatar.cc/150?img=9',
                'nama_perusahaan' => 'Makassar Realty Group',
                'email' => 'joko.santoso@mrg.com',
                'telepon' => '083432109876',
                'foto' => 'https://picsum.photos/800/600?random=9',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Kartika Sari',
                'nib' => '3344556677889',
                'alamat' => 'Jl. Pahlawan No. 100, Bogor',
                'foto_profile' => 'https://i.pravatar.cc/150?img=10',
                'nama_perusahaan' => 'Bogor Land Development',
                'email' => 'kartika.sari@bld.com',
                'telepon' => '085654321098',
                'foto' => 'https://picsum.photos/800/600?random=10',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Lukman Hakim',
                'nib' => '6677889900112',
                'alamat' => 'Jl. Tunjungan No. 110, Surabaya',
                'foto_profile' => 'https://i.pravatar.cc/150?img=11',
                'nama_perusahaan' => 'East Java Properti',
                'email' => 'lukman.hakim@ejp.com',
                'telepon' => '087876543210',
                'foto' => 'https://picsum.photos/800/600?random=11',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Maria Angelina',
                'nib' => '9900112233445',
                'alamat' => 'Jl. Kartini No. 120, Batam',
                'foto_profile' => 'https://i.pravatar.cc/150?img=12',
                'nama_perusahaan' => 'Batam Island Realty',
                'email' => 'maria.angelina@bir.com',
                'telepon' => '089098765432',
                'foto' => 'https://picsum.photos/800/600?random=12',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Nanda Pratama',
                'nib' => '2468013579246',
                'alamat' => 'Jl. Sisingamangaraja No. 130, Palembang',
                'foto_profile' => 'https://i.pravatar.cc/150?img=13',
                'nama_perusahaan' => 'South Sumatra Realty',
                'email' => 'nanda.pratama@ssr.com',
                'telepon' => '081230198765',
                'foto' => 'https://picsum.photos/800/600?random=13',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Olivia Wijaya',
                'nib' => '1357924680135',
                'alamat' => 'Jl. Teuku Umar No. 140, Samarinda',
                'foto_profile' => 'https://i.pravatar.cc/150?img=14',
                'nama_perusahaan' => 'Borneo Properti Agen',
                'email' => 'olivia.wijaya@bpa.com',
                'telepon' => '082341209876',
                'foto' => 'https://picsum.photos/800/600?random=14',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Pramudya Hadi',
                'nib' => '4680135792468',
                'alamat' => 'Jl. Margonda Raya No. 150, Depok',
                'foto_profile' => 'https://i.pravatar.cc/150?img=15',
                'nama_perusahaan' => 'Depok Property Expert',
                'email' => 'pramudya.hadi@dpe.com',
                'telepon' => '083452310987',
                'foto' => 'https://picsum.photos/800/600?random=15',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Rina Sasmita',
                'nib' => '7901357924680',
                'alamat' => 'Jl. Setiabudi No. 160, Bandung',
                'foto_profile' => 'https://i.pravatar.cc/150?img=16',
                'nama_perusahaan' => 'Bandung Properti Cerdas',
                'email' => 'rina.sasmita@bpc.com',
                'telepon' => '085674532109',
                'foto' => 'https://picsum.photos/800/600?random=16',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Satriya Utama',
                'nib' => '0135792468013',
                'alamat' => 'Jl. Dr. Sutomo No. 170, Malang',
                'foto_profile' => 'https://i.pravatar.cc/150?img=17',
                'nama_perusahaan' => 'Malang Property Center',
                'email' => 'satriya.utama@mpc.com',
                'telepon' => '087896754321',
                'foto' => 'https://picsum.photos/800/600?random=17',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Tiara Permata',
                'nib' => '3579246801357',
                'alamat' => 'Jl. Sutan Syahrir No. 180, Padang',
                'foto_profile' => 'https://i.pravatar.cc/150?img=18',
                'nama_perusahaan' => 'West Sumatra Property',
                'email' => 'tiara.permata@wsp.com',
                'telepon' => '089018976543',
                'foto' => 'https://picsum.photos/800/600?random=18',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Vicky Adrian',
                'nib' => '6802468013579',
                'alamat' => 'Jl. Yos Sudarso No. 190, Manado',
                'foto_profile' => 'https://i.pravatar.cc/150?img=19',
                'nama_perusahaan' => 'North Sulawesi Realty',
                'email' => 'vicky.adrian@nsr.com',
                'telepon' => '081132109876',
                'foto' => 'https://picsum.photos/800/600?random=19',
                'aktif' => true,
            ],
            [
                'user_id' => null,
                'nama' => 'Wulan Sari',
                'nib' => '9013579246801',
                'alamat' => 'Jl. Pemuda No. 200, Palu',
                'foto_profile' => 'https://i.pravatar.cc/150?img=20',
                'nama_perusahaan' => 'Central Sulawesi Properti',
                'email' => 'wulan.sari@csp.com',
                'telepon' => '082243210987',
                'foto' => 'https://picsum.photos/800/600?random=20',
                'aktif' => false, // Contoh data yang tidak aktif
            ],
        ];

        DB::table('agents')->insert($agents);
    }
}
