<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        // $properties = [
        //     // 1. Rumah Mewah Jakarta (Jual)
        //     [
        //         'agent_id' => 1,
        //         'kategori_id' => 1, // Rumah
        //         'title' => 'Rumah Mewah Modern di Kemang, Jakarta Selatan',
        //         'deskripsi' => 'Rumah modern dengan desain minimalis 2 lantai, kolam renang mini, dekat pusat perbelanjaan dan sekolah internasional.',
        //         'alamat' => 'Jl. Pangeran Antasari No. 12',
        //         'kabupaten_kota' => 'Jakarta Selatan',
        //         'provinsi' => 'DKI Jakarta',
        //         'harga' => 4500000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '081123456789',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 4,
        //         'kamar_mandi' => 4,
        //         'luas_tanah' => 250,
        //         'luas_bangunan' => 300,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 5500,
        //         'kamar_tidur_pembantu' => 1,
        //         'jumlah_lantai' => 2,
        //         'kondisi_perabotan' => 'Semi Furnished',
        //         'hadap' => 'Timur',
        //         'sumber_air' => 'PAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1560448075-bb485b67c3a0?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1570129477038-f1c5034c4f34?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 2. Apartemen Bandung (Sewa)
        //     [
        //         'agent_id' => 2,
        //         'kategori_id' => 3, // Apartemen
        //         'title' => 'Apartemen Studio Full Furnished Cihampelas, Bandung',
        //         'deskripsi' => 'Apartemen dengan fasilitas lengkap (kolam renang, gym) di lokasi strategis Dago-Cihampelas. Cocok untuk mahasiswa atau pekerja.',
        //         'alamat' => 'Jl. Dago No. 25 Tower B',
        //         'kabupaten_kota' => 'Bandung',
        //         'provinsi' => 'Jawa Barat',
        //         'harga' => 4500000,
        //         'satuan_harga' => 'per bulan',
        //         'whatsapp' => '082234567890',
        //         'tersedia' => true,
        //         'tipe' => 'sewa',
        //         'kamar_tidur' => 1,
        //         'kamar_mandi' => 1,
        //         'luas_tanah' => 0,
        //         'luas_bangunan' => 35,
        //         'sertifikat' => null,
        //         'daya_listrik' => 2200,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 1,
        //         'kondisi_perabotan' => 'Full Furnished',
        //         'hadap' => 'Selatan',
        //         'sumber_air' => 'PDAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1565182999561-18d7f0a3497f?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1600585153837-1d7d2d29fcca?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1540375253896-147a3297a7a7?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 3. Villa Bali (Sewa Harian)
        //     [
        //         'agent_id' => 3,
        //         'kategori_id' => 11, // Villa
        //         'title' => 'Villa Eksotis Kolam Renang Pribadi di Ubud, Bali',
        //         'deskripsi' => 'Villa dengan pemandangan sawah yang menenangkan dan kolam renang pribadi. Ideal untuk liburan/honeymoon.',
        //         'alamat' => 'Jl. Raya Ubud No. 5',
        //         'kabupaten_kota' => 'Gianyar',
        //         'provinsi' => 'Bali',
        //         'harga' => 1800000,
        //         'satuan_harga' => 'per malam',
        //         'whatsapp' => '083876543210',
        //         'tersedia' => true,
        //         'tipe' => 'sewa',
        //         'kamar_tidur' => 3,
        //         'kamar_mandi' => 3,
        //         'luas_tanah' => 450,
        //         'luas_bangunan' => 280,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 5500,
        //         'kamar_tidur_pembantu' => 1,
        //         'jumlah_lantai' => 1,
        //         'kondisi_perabotan' => 'Full Furnished',
        //         'hadap' => 'Utara',
        //         'sumber_air' => 'Sumur Bor',
        //         'hook' => 'Ya',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1600585154174-43e27e23f04b?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1582268481303-3e053a479b12?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 4. Tanah Kavling Surabaya (Jual)
        //     [
        //         'agent_id' => 4,
        //         'kategori_id' => 2, // Tanah
        //         'title' => 'Tanah Kavling Siap Bangun Dekat Tol, Surabaya Timur',
        //         'deskripsi' => 'Tanah datar di lokasi perumahan elit, bebas banjir, cocok untuk investasi atau hunian.',
        //         'alamat' => 'Jl. Raya Merr No. 50',
        //         'kabupaten_kota' => 'Surabaya',
        //         'provinsi' => 'Jawa Timur',
        //         'harga' => 1500000,
        //         'satuan_harga' => 'per meter persegi',
        //         'whatsapp' => '085567890123',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 0,
        //         'luas_tanah' => 450,
        //         'luas_bangunan' => 0,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 0,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 0,
        //         'kondisi_perabotan' => 'Tidak Ada',
        //         'hadap' => 'Barat',
        //         'sumber_air' => 'Tidak Ada',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1534349735949-563e46e8b4e7?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1507567823528-7694f4c28f1e?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 5. Ruko Medan (Jual)
        //     [
        //         'agent_id' => 5,
        //         'kategori_id' => 4, // Ruko
        //         'title' => 'Ruko Strategis 3 Lantai di Pusat Kota Medan',
        //         'deskripsi' => 'Lokasi emas, cocok untuk usaha atau perkantoran. Akses mudah ke jalan utama.',
        //         'alamat' => 'Jl. Sudirman No. 55',
        //         'kabupaten_kota' => 'Medan',
        //         'provinsi' => 'Sumatera Utara',
        //         'harga' => 3800000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '087789012345',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 3,
        //         'luas_tanah' => 100,
        //         'luas_bangunan' => 280,
        //         'sertifikat' => 'HGB',
        //         'daya_listrik' => 7700,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 3,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Utara',
        //         'sumber_air' => 'PAM',
        //         'hook' => 'Ya',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1497215728101-856f4ea42174?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1531545514256-4299b4009228?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 6. Kantor Jakarta (Sewa Tahunan)
        //     [
        //         'agent_id' => 6,
        //         'kategori_id' => 5, // Kantor
        //         'title' => 'Ruang Kantor Premium Grade A Kuningan',
        //         'deskripsi' => 'Ruang kantor siap pakai di gedung bergengsi. Dekat pusat bisnis Jakarta.',
        //         'alamat' => 'Jl. HR Rasuna Said Kav. 60',
        //         'kabupaten_kota' => 'Jakarta Selatan',
        //         'provinsi' => 'DKI Jakarta',
        //         'harga' => 500000000,
        //         'satuan_harga' => 'per tahun',
        //         'whatsapp' => '089901234567',
        //         'tersedia' => true,
        //         'tipe' => 'sewa',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 0,
        //         'luas_tanah' => 0,
        //         'luas_bangunan' => 150,
        //         'sertifikat' => null,
        //         'daya_listrik' => 15000,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 1,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Barat Daya',
        //         'sumber_air' => 'Gedung',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1517048676732-d65bc937f952?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 7. Rumah Denpasar (Jual)
        //     [
        //         'agent_id' => 7,
        //         'kategori_id' => 1, // Rumah
        //         'title' => 'Rumah Minimalis Dekat Pantai Sanur, Denpasar',
        //         'deskripsi' => 'Hunian nyaman dengan akses mudah ke pantai dan pusat kota.',
        //         'alamat' => 'Jl. Hayam Wuruk No. 70',
        //         'kabupaten_kota' => 'Denpasar',
        //         'provinsi' => 'Bali',
        //         'harga' => 1800000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '081210987654',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 3,
        //         'kamar_mandi' => 2,
        //         'luas_tanah' => 150,
        //         'luas_bangunan' => 120,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 3500,
        //         'kamar_tidur_pembantu' => 0,
        //         'jumlah_lantai' => 1,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Selatan',
        //         'sumber_air' => 'PDAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1518780664697-5537f22ec5d6?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1505691938895-1758d7dfa2ce?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 8. Tanah Kavling Yogyakarta (Jual)
        //     [
        //         'agent_id' => 8,
        //         'kategori_id' => 2, // Tanah
        //         'title' => 'Tanah di Area Pengembangan Bisnis, Yogyakarta',
        //         'deskripsi' => 'Tanah hook di jalan utama. Cocok untuk dibangun Ruko atau Kantor.',
        //         'alamat' => 'Jl. Veteran No. 80',
        //         'kabupaten_kota' => 'Yogyakarta',
        //         'provinsi' => 'DI Yogyakarta',
        //         'harga' => 3000000,
        //         'satuan_harga' => 'per meter persegi',
        //         'whatsapp' => '082321098765',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 0,
        //         'luas_tanah' => 500,
        //         'luas_bangunan' => 0,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 0,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 0,
        //         'kondisi_perabotan' => 'Tidak Ada',
        //         'hadap' => 'Timur',
        //         'sumber_air' => 'Tidak Ada',
        //         'hook' => 'Ya',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1541334994269-00109f0298a0?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1508920155057-0841571f547c?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 9. Ruko Makassar (Sewa)
        //     [
        //         'agent_id' => 9,
        //         'kategori_id' => 4, // Ruko
        //         'title' => 'Ruko 2 Lantai Dekat Kampus, Makassar',
        //         'deskripsi' => 'Cocok untuk minimarket atau kafe, ramai mahasiswa. Area parkir luas.',
        //         'alamat' => 'Jl. Ahmad Yani No. 90',
        //         'kabupaten_kota' => 'Makassar',
        //         'provinsi' => 'Sulawesi Selatan',
        //         'harga' => 150000000,
        //         'satuan_harga' => 'per tahun',
        //         'whatsapp' => '083432109876',
        //         'tersedia' => true,
        //         'tipe' => 'sewa',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 2,
        //         'luas_tanah' => 80,
        //         'luas_bangunan' => 140,
        //         'sertifikat' => 'HGB',
        //         'daya_listrik' => 5500,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 2,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Selatan',
        //         'sumber_air' => 'PAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1588661608836-394998797f1f?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1579304135540-870f20d58847?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 10. Rumah Bogor (Jual)
        //     [
        //         'agent_id' => 10,
        //         'kategori_id' => 1, // Rumah
        //         'title' => 'Rumah Klasik Asri di Sentul City, Bogor',
        //         'deskripsi' => 'Lingkungan sejuk dan aman, fasilitas perumahan lengkap, 3 kamar tidur utama.',
        //         'alamat' => 'Jl. Pahlawan No. 100',
        //         'kabupaten_kota' => 'Bogor',
        //         'provinsi' => 'Jawa Barat',
        //         'harga' => 3200000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '085654321098',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 3,
        //         'kamar_mandi' => 3,
        //         'luas_tanah' => 300,
        //         'luas_bangunan' => 220,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 4400,
        //         'kamar_tidur_pembantu' => 1,
        //         'jumlah_lantai' => 2,
        //         'kondisi_perabotan' => 'Semi Furnished',
        //         'hadap' => 'Utara',
        //         'sumber_air' => 'PAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1600047509807-ba8f074740e5?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1576941089067-2de3c901e126?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 11. Apartemen Surabaya (Jual)
        //     [
        //         'agent_id' => 11,
        //         'kategori_id' => 3, // Apartemen
        //         'title' => 'Apartemen View Kota 2BR di Pusat Surabaya',
        //         'deskripsi' => 'Cocok untuk investasi atau hunian, dekat Tunjungan Plaza.',
        //         'alamat' => 'Jl. Tunjungan No. 110',
        //         'kabupaten_kota' => 'Surabaya',
        //         'provinsi' => 'Jawa Timur',
        //         'harga' => 950000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '087876543210',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 2,
        //         'kamar_mandi' => 1,
        //         'luas_tanah' => 0,
        //         'luas_bangunan' => 70,
        //         'sertifikat' => 'Strata Title',
        //         'daya_listrik' => 3500,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 1,
        //         'kondisi_perabotan' => 'Full Furnished',
        //         'hadap' => 'Timur Laut',
        //         'sumber_air' => 'PDAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1543269865-c3f2b6041042?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1627963391786-9a25b16e4548?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 12. Ruko Batam (Jual)
        //     [
        //         'agent_id' => 12,
        //         'kategori_id' => 4, // Ruko
        //         'title' => 'Ruko Baru 3 Lantai di Area Industri Batam',
        //         'deskripsi' => 'Dekat pelabuhan dan kawasan industri, cocok untuk kantor cabang.',
        //         'alamat' => 'Jl. Kartini No. 120',
        //         'kabupaten_kota' => 'Batam',
        //         'provinsi' => 'Kepulauan Riau',
        //         'harga' => 2100000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '089098765432',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 3,
        //         'luas_tanah' => 90,
        //         'luas_bangunan' => 250,
        //         'sertifikat' => 'HGB',
        //         'daya_listrik' => 7700,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 3,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Selatan',
        //         'sumber_air' => 'PAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1516245834211-1a0e8d022b72?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1506548232971-8933b28b610c?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 13. Rumah Palembang (Sewa Tahunan)
        //     [
        //         'agent_id' => 13,
        //         'kategori_id' => 1, // Rumah
        //         'title' => 'Rumah Keluarga Asri di Komplek Elit Palembang',
        //         'deskripsi' => 'Lingkungan tenang dan aman, dekat fasilitas umum, cocok untuk keluarga.',
        //         'alamat' => 'Jl. Sisingamangaraja No. 130',
        //         'kabupaten_kota' => 'Palembang',
        //         'provinsi' => 'Sumatera Selatan',
        //         'harga' => 75000000,
        //         'satuan_harga' => 'per tahun',
        //         'whatsapp' => '081230198765',
        //         'tersedia' => true,
        //         'tipe' => 'sewa',
        //         'kamar_tidur' => 4,
        //         'kamar_mandi' => 3,
        //         'luas_tanah' => 200,
        //         'luas_bangunan' => 180,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 4400,
        //         'kamar_tidur_pembantu' => 1,
        //         'jumlah_lantai' => 2,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Barat',
        //         'sumber_air' => 'PDAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1583608149830-10821867e108?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1600566753086-f7b2dd6e220a?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 14. Tanah Samarinda (Jual)
        //     [
        //         'agent_id' => 14,
        //         'kategori_id' => 2, // Tanah
        //         'title' => 'Tanah Komersial di Tepi Jalan Utama Samarinda',
        //         'deskripsi' => 'Zona kuning, siap bangun. Cocok untuk proyek komersial skala besar.',
        //         'alamat' => 'Jl. Teuku Umar No. 140',
        //         'kabupaten_kota' => 'Samarinda',
        //         'provinsi' => 'Kalimantan Timur',
        //         'harga' => 2500000,
        //         'satuan_harga' => 'per meter persegi',
        //         'whatsapp' => '082341209876',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 0,
        //         'luas_tanah' => 1000,
        //         'luas_bangunan' => 0,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 0,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 0,
        //         'kondisi_perabotan' => 'Tidak Ada',
        //         'hadap' => 'Utara',
        //         'sumber_air' => 'Tidak Ada',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1560934141-f62c5b057864?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1549419163-491c7820a4ce?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 15. Rumah Depok (Jual)
        //     [
        //         'agent_id' => 15,
        //         'kategori_id' => 1, // Rumah
        //         'title' => 'Rumah Baru Minimalis di Margonda, Depok',
        //         'deskripsi' => 'Akses langsung ke jalan utama Margonda, dekat kampus dan stasiun KRL. Cocok untuk hunian atau investasi.',
        //         'alamat' => 'Jl. Margonda Raya No. 150',
        //         'kabupaten_kota' => 'Depok',
        //         'provinsi' => 'Jawa Barat',
        //         'harga' => 1350000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '083452310987',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 3,
        //         'kamar_mandi' => 2,
        //         'luas_tanah' => 120,
        //         'luas_bangunan' => 100,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 2200,
        //         'kamar_tidur_pembantu' => 0,
        //         'jumlah_lantai' => 2,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Selatan',
        //         'sumber_air' => 'Sumur Bor',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1593809228588-444a7090886a?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1594916813292-e427e02554d6?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 16. Apartemen Bandung (Sewa)
        //     [
        //         'agent_id' => 16,
        //         'kategori_id' => 3, // Apartemen
        //         'title' => 'Apartemen 1BR View Gunung di Setiabudi',
        //         'deskripsi' => 'Pemandangan indah, udara sejuk. Full furnished siap huni.',
        //         'alamat' => 'Jl. Setiabudi No. 160 Tower C',
        //         'kabupaten_kota' => 'Bandung',
        //         'provinsi' => 'Jawa Barat',
        //         'harga' => 3500000,
        //         'satuan_harga' => 'per bulan',
        //         'whatsapp' => '085674532109',
        //         'tersedia' => true,
        //         'tipe' => 'sewa',
        //         'kamar_tidur' => 1,
        //         'kamar_mandi' => 1,
        //         'luas_tanah' => 0,
        //         'luas_bangunan' => 45,
        //         'sertifikat' => null,
        //         'daya_listrik' => 2200,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 1,
        //         'kondisi_perabotan' => 'Full Furnished',
        //         'hadap' => 'Utara',
        //         'sumber_air' => 'PDAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1549491917-8e104f981e85?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1550970005-950cc889e436?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 17. Rumah Malang (Jual)
        //     [
        //         'agent_id' => 17,
        //         'kategori_id' => 1, // Rumah
        //         'title' => 'Rumah Cantik di Kota Malang Dekat Wisata',
        //         'deskripsi' => 'Desain Skandinavian, dekat pusat kota dan tempat wisata. Harga menarik.',
        //         'alamat' => 'Jl. Dr. Sutomo No. 170',
        //         'kabupaten_kota' => 'Malang',
        //         'provinsi' => 'Jawa Timur',
        //         'harga' => 850000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '087896754321',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 3,
        //         'kamar_mandi' => 2,
        //         'luas_tanah' => 150,
        //         'luas_bangunan' => 120,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 2200,
        //         'kamar_tidur_pembantu' => 0,
        //         'jumlah_lantai' => 1,
        //         'kondisi_perabotan' => 'Semi Furnished',
        //         'hadap' => 'Barat',
        //         'sumber_air' => 'PDAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1522771739846-791690a73d84?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1550581190-9519ae7e96b8?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 18. Kantor Padang (Sewa)
        //     [
        //         'agent_id' => 18,
        //         'kategori_id' => 5, // Kantor
        //         'title' => 'Gedung Kantor Minimalis 2 Lantai di Padang',
        //         'deskripsi' => 'Lokasi strategis di pusat kota. Area parkir memadai. Siap pakai.',
        //         'alamat' => 'Jl. Sutan Syahrir No. 180',
        //         'kabupaten_kota' => 'Padang',
        //         'provinsi' => 'Sumatera Barat',
        //         'harga' => 120000000,
        //         'satuan_harga' => 'per tahun',
        //         'whatsapp' => '089018976543',
        //         'tersedia' => true,
        //         'tipe' => 'sewa',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 4,
        //         'luas_tanah' => 250,
        //         'luas_bangunan' => 350,
        //         'sertifikat' => 'HGB',
        //         'daya_listrik' => 10000,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 2,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Timur',
        //         'sumber_air' => 'PAM',
        //         'hook' => 'Ya',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1549882298-59c043e06a38?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1557804506-669c5e20d53c?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 19. Tanah Manado (Jual)
        //     [
        //         'agent_id' => 19,
        //         'kategori_id' => 2, // Tanah
        //         'title' => 'Tanah di Pesisir Pantai Manado View Laut',
        //         'deskripsi' => 'Tanah datar ideal untuk villa atau resort. Pemandangan laut yang menakjubkan.',
        //         'alamat' => 'Jl. Yos Sudarso No. 190',
        //         'kabupaten_kota' => 'Manado',
        //         'provinsi' => 'Sulawesi Utara',
        //         'harga' => 1000000,
        //         'satuan_harga' => 'per meter persegi',
        //         'whatsapp' => '081132109876',
        //         'tersedia' => true,
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 0,
        //         'kamar_mandi' => 0,
        //         'luas_tanah' => 2000,
        //         'luas_bangunan' => 0,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 0,
        //         'kamar_tidur_pembantu' => null,
        //         'jumlah_lantai' => 0,
        //         'kondisi_perabotan' => 'Tidak Ada',
        //         'hadap' => 'Barat',
        //         'sumber_air' => 'Tidak Ada',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1541334947941-6972cc945d8b?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1563853153-f728c3196c3a?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        //     // 20. Rumah Palu (Jual)
        //     [
        //         'agent_id' => 20,
        //         'kategori_id' => 1, // Rumah
        //         'title' => 'Rumah Baru 2 Lantai di Pusat Kota Palu',
        //         'deskripsi' => 'Lokasi strategis, dekat dengan fasilitas kota. Desain minimalis modern.',
        //         'alamat' => 'Jl. Pemuda No. 200',
        //         'kabupaten_kota' => 'Palu',
        //         'provinsi' => 'Sulawesi Tengah',
        //         'harga' => 900000000,
        //         'satuan_harga' => 'per unit',
        //         'whatsapp' => '082243210987',
        //         'tersedia' => false, // Tidak Aktif
        //         'tipe' => 'jual',
        //         'kamar_tidur' => 3,
        //         'kamar_mandi' => 2,
        //         'luas_tanah' => 180,
        //         'luas_bangunan' => 150,
        //         'sertifikat' => 'SHM',
        //         'daya_listrik' => 3500,
        //         'kamar_tidur_pembantu' => 0,
        //         'jumlah_lantai' => 2,
        //         'kondisi_perabotan' => 'Kosong',
        //         'hadap' => 'Timur',
        //         'sumber_air' => 'PDAM',
        //         'hook' => 'Tidak',
        //         'foto_gallery' => json_encode([
        //             'https://images.unsplash.com/photo-1600585152857-4b7b2521f7c7?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //             'https://images.unsplash.com/photo-1596766782247-49f992666d6d?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&h=600',
        //         ]),
        //     ],
        // ];


        $properties = [
            // KATEGORI 1: RUMAH (ID: 1) - 6 ENTRI
            [
                'agent_id' => 1,
                'kategori_id' => 1,
                'title' => 'Rumah Mewah Modern di Kemang, Jakarta Selatan',
                'deskripsi' => 'Rumah modern dengan desain minimalis 2 lantai, kolam renang mini, dekat pusat perbelanjaan dan sekolah internasional.',
                'alamat' => 'Jl. Pangeran Antasari No. 12',
                'kabupaten_kota' => 'Jakarta Selatan',
                'provinsi' => 'DKI Jakarta',
                'harga' => 4500000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '081123456789',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 4, 'kamar_mandi' => 4,
                'luas_tanah' => 250, 'luas_bangunan' => 300,
                'sertifikat' => 'SHM', 'daya_listrik' => 5500,
                'kamar_tidur_pembantu' => 1, 'jumlah_lantai' => 2,
                'kondisi_perabotan' => 'Semi Furnished', 'hadap' => 'Timur',
                'sumber_air' => 'PAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/image-illustration/modern-house-exterior-day-light-600w-2594770339.jpg', // Rumah Modern
                    'https://www.shutterstock.com/image-illustration/modern-house-exterior-day-light-600w-2594770371.jpg',  // Interior
                    'https://www.shutterstock.com/image-illustration/modern-house-exterior-day-light-600w-2594770375.jpg',  // Eksterior
                ]),
            ],
            [
                'agent_id' => 2,
                'kategori_id' => 1,
                'title' => 'Rumah Minimalis Dekat Pantai Sanur, Denpasar',
                'deskripsi' => 'Hunian nyaman dengan akses mudah ke pantai dan pusat kota.',
                'alamat' => 'Jl. Hayam Wuruk No. 70',
                'kabupaten_kota' => 'Denpasar',
                'provinsi' => 'Bali',
                'harga' => 1800000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '081210987654',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 3, 'kamar_mandi' => 2,
                'luas_tanah' => 150, 'luas_bangunan' => 120,
                'sertifikat' => 'SHM', 'daya_listrik' => 3500,
                'kamar_tidur_pembantu' => 0, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Selatan',
                'sumber_air' => 'PDAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2258275569/display_1500/stock-photo-modern-house-exterior-day-light-with-lawn-grass-d-rendering-2258275569.jpg',  // Pagar
                    'https://www.shutterstock.com/shutterstock/photos/2163517557/display_1500/stock-photo--d-rendering-of-white-modern-house-with-concrete-floor-and-lawn-yard-2163517557.jpg', // Rumah 1 Lantai
                    'https://www.shutterstock.com/shutterstock/photos/1862598859/display_1500/stock-photo-small-modern-house-d-illustration-1862598859.jpg', // Rumah 1 Lantai
                ]),
            ],
            [
                'agent_id' => 1,
                'kategori_id' => 1,
                'title' => 'Rumah Klasik Asri di Sentul City, Bogor',
                'deskripsi' => 'Lingkungan sejuk dan aman, fasilitas perumahan lengkap, 3 kamar tidur utama.',
                'alamat' => 'Jl. Pahlawan No. 100',
                'kabupaten_kota' => 'Bogor',
                'provinsi' => 'Jawa Barat',
                'harga' => 3200000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '085654321098',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 3, 'kamar_mandi' => 3,
                'luas_tanah' => 300, 'luas_bangunan' => 220,
                'sertifikat' => 'SHM', 'daya_listrik' => 4400,
                'kamar_tidur_pembantu' => 1, 'jumlah_lantai' => 2,
                'kondisi_perabotan' => 'Semi Furnished', 'hadap' => 'Utara',
                'sumber_air' => 'PAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2442881421/display_1500/stock-photo-night-view-of-modern-house-with-solar-panels-and-swimming-pool-d-rendering-2442881421.jpg', // Rumah Klasik
                    'https://www.shutterstock.com/shutterstock/photos/2201305337/display_1500/stock-photo--d-visualization-of-a-modern-house-house-with-large-windows-and-a-terrace-modern-architecture-2201305337.jpg', // Halaman
                    'https://www.shutterstock.com/shutterstock/photos/2202255151/display_1500/stock-photo--d-visualization-of-a-modern-house-with-a-swimming-pool-luxury-architecture-2202255151.jpg', // Halaman
                ]),
            ],
            [
                'agent_id' => 1,
                'kategori_id' => 1,
                'title' => 'Rumah Keluarga Asri di Komplek Elit Palembang (Sewa)',
                'deskripsi' => 'Lingkungan tenang dan aman, dekat fasilitas umum, cocok untuk keluarga.',
                'alamat' => 'Jl. Sisingamangaraja No. 130',
                'kabupaten_kota' => 'Palembang',
                'provinsi' => 'Sumatera Selatan',
                'harga' => 75000000,
                'satuan_harga' => 'per tahun',
                'whatsapp' => '081230198765',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 4, 'kamar_mandi' => 3,
                'luas_tanah' => 200, 'luas_bangunan' => 180,
                'sertifikat' => 'SHM', 'daya_listrik' => 4400,
                'kamar_tidur_pembantu' => 1, 'jumlah_lantai' => 2,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Barat',
                'sumber_air' => 'PDAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2499058629/display_1500/stock-photo-cottage-house-exterior-day-light-with-lawn-grass-d-rendering-2499058629.jpg', // Rumah 2 Lantai
                    'https://www.shutterstock.com/shutterstock/photos/1216283266/display_1500/stock-photo--d-rendering-of-a-house-with-garden-undergoing-renovation-1216283266.jpg', // Ruang Tamu
                    'https://www.shutterstock.com/shutterstock/photos/1220524492/display_1500/stock-photo--d-rendering-of-a-house-with-garden-undergoing-renovation-1220524492.jpg', // Ruang Tamu
                ]),
            ],
            [
                'agent_id' => 2,
                'kategori_id' => 1,
                'title' => 'Rumah Baru Minimalis di Margonda, Depok',
                'deskripsi' => 'Akses langsung ke jalan utama Margonda, dekat kampus dan stasiun KRL. Cocok untuk hunian atau investasi.',
                'alamat' => 'Jl. Margonda Raya No. 150',
                'kabupaten_kota' => 'Depok',
                'provinsi' => 'Jawa Barat',
                'harga' => 1350000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '083452310987',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 3, 'kamar_mandi' => 2,
                'luas_tanah' => 120, 'luas_bangunan' => 100,
                'sertifikat' => 'SHM', 'daya_listrik' => 2200,
                'kamar_tidur_pembantu' => 0, 'jumlah_lantai' => 2,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Selatan',
                'sumber_air' => 'Sumur Bor', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2499768499/display_1500/stock-photo-modern-house-exterior-day-light-with-lawn-grass-d-rendering-2499768499.jpg', // Rumah Minimalis
                    'https://www.shutterstock.com/shutterstock/photos/2501815675/display_1500/stock-photo-modern-house-exterior-day-light-with-lawn-grass-d-rendering-2501815675.jpg', // Dapur
                    'https://www.shutterstock.com/shutterstock/photos/2499768507/display_1500/stock-photo-modern-house-exterior-day-light-with-lawn-grass-d-rendering-2499768507.jpg', // Dapur
                ]),
            ],
            [
                'agent_id' => 4,
                'kategori_id' => 1,
                'title' => 'Rumah Cantik di Kota Malang Dekat Wisata',
                'deskripsi' => 'Desain Skandinavian, dekat pusat kota dan tempat wisata. Harga menarik.',
                'alamat' => 'Jl. Dr. Sutomo No. 170',
                'kabupaten_kota' => 'Malang',
                'provinsi' => 'Jawa Timur',
                'harga' => 850000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '087896754321',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 3, 'kamar_mandi' => 2,
                'luas_tanah' => 150, 'luas_bangunan' => 120,
                'sertifikat' => 'SHM', 'daya_listrik' => 2200,
                'kamar_tidur_pembantu' => 0, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Semi Furnished', 'hadap' => 'Barat',
                'sumber_air' => 'PDAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2503037471/display_1500/stock-photo-modern-house-exterior-day-light-with-lawn-grass-d-rendering-2503037471.jpg', // Rumah Skandinavia
                    'https://www.shutterstock.com/shutterstock/photos/2483421955/display_1500/stock-photo-contemporary-house-exterior-daylight-with-lawn-grass-d-rendering-2483421955.jpg', // Kamar Tidur
                    'https://www.shutterstock.com/shutterstock/photos/2501815675/display_1500/stock-photo-modern-house-exterior-day-light-with-lawn-grass-d-rendering-2501815675.jpg', // Kamar Tidur
                ]),
            ],
            
            
            // KATEGORI 2: TANAH (ID: 2) - 4 ENTRI
            [
                'agent_id' => 4,
                'kategori_id' => 2,
                'title' => 'Tanah Kavling Siap Bangun Dekat Tol, Surabaya Timur',
                'deskripsi' => 'Tanah datar di lokasi perumahan elit, bebas banjir, cocok untuk investasi atau hunian.',
                'alamat' => 'Jl. Raya Merr No. 50',
                'kabupaten_kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'harga' => 1500000,
                'satuan_harga' => 'per meter persegi',
                'whatsapp' => '085567890123',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 0, 'kamar_mandi' => 0,
                'luas_tanah' => 450, 'luas_bangunan' => 0,
                'sertifikat' => 'SHM', 'daya_listrik' => 0,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 0,
                'kondisi_perabotan' => 'Tidak Ada', 'hadap' => 'Barat',
                'sumber_air' => 'Tidak Ada', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2413054113/display_1500/stock-photo--d-rendering-of-a-modern-apartment-building-in-the-evening-2413054113.jpg', // Tanah Lapang
                    'https://www.shutterstock.com/shutterstock/photos/1248556306/display_1500/stock-photo-modern-apartment-buildings-in-a-green-residential-area-in-the-city-d-rendering-1248556306.jpg', // Pemandangan Alam
                    'https://www.shutterstock.com/shutterstock/photos/1254055720/display_1500/stock-photo-modern-apartment-buildings-in-the-city-d-rendering-1254055720.jpg', // Pemandangan Alam
                ]),
            ],
            [
                'agent_id' => 3,
                'kategori_id' => 2,
                'title' => 'Tanah di Area Pengembangan Bisnis, Yogyakarta (Hook)',
                'deskripsi' => 'Tanah hook di jalan utama. Cocok untuk dibangun Ruko atau Kantor.',
                'alamat' => 'Jl. Veteran No. 80',
                'kabupaten_kota' => 'Yogyakarta',
                'provinsi' => 'DI Yogyakarta',
                'harga' => 3000000,
                'satuan_harga' => 'per meter persegi',
                'whatsapp' => '082321098765',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 0, 'kamar_mandi' => 0,
                'luas_tanah' => 500, 'luas_bangunan' => 0,
                'sertifikat' => 'SHM', 'daya_listrik' => 0,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 0,
                'kondisi_perabotan' => 'Tidak Ada', 'hadap' => 'Timur',
                'sumber_air' => 'Tidak Ada', 'hook' => 'Ya',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2149873455/display_1500/stock-photo-modern-townhouse-design-d-rendering-2149873455.jpg', // Tanah di Persimpangan
                    'https://www.shutterstock.com/shutterstock/photos/2149873451/display_1500/stock-photo-modern-townhouse-design-d-rendering-2149873451.jpg', // Jalan
                    'https://www.shutterstock.com/shutterstock/photos/2086104178/display_1500/stock-photo--d-illustration-of-apartment-building-in-hilly-area-with-balcony-terrace-china-2086104178.jpg', // Jalan
                ]),
            ],
            [
                'agent_id' => 2,
                'kategori_id' => 2,
                'title' => 'Tanah Komersial di Tepi Jalan Utama Samarinda',
                'deskripsi' => 'Zona kuning, siap bangun. Cocok untuk proyek komersial skala besar.',
                'alamat' => 'Jl. Teuku Umar No. 140',
                'kabupaten_kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'harga' => 2500000,
                'satuan_harga' => 'per meter persegi',
                'whatsapp' => '082341209876',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 0, 'kamar_mandi' => 0,
                'luas_tanah' => 1000, 'luas_bangunan' => 0,
                'sertifikat' => 'SHM', 'daya_listrik' => 0,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 0,
                'kondisi_perabotan' => 'Tidak Ada', 'hadap' => 'Utara',
                'sumber_air' => 'Tidak Ada', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2101133932/display_1500/stock-photo-hospital-building-design-entrance-space-drone-view-of-contemporary-illustration-d-artwork-2101133932.jpg', // Pemandangan Tanah
                    'https://www.shutterstock.com/shutterstock/photos/2023475540/display_1500/stock-photo--d-rendering-of-tropical-house-exterior-2023475540.jpg', // Papan Proyek
                    'https://www.shutterstock.com/shutterstock/photos/2479489863/display_1500/stock-photo--d-rendering-of-a-modern-multi-story-office-building-with-large-glass-windows-and-several-outdoor-2479489863.jpg', // Papan Proyek
                ]),
            ],
            [
                'agent_id' => 3,
                'kategori_id' => 2,
                'title' => 'Tanah di Pesisir Pantai Manado View Laut',
                'deskripsi' => 'Tanah datar ideal untuk villa atau resort. Pemandangan laut yang menakjubkan.',
                'alamat' => 'Jl. Yos Sudarso No. 190',
                'kabupaten_kota' => 'Manado',
                'provinsi' => 'Sulawesi Utara',
                'harga' => 1000000,
                'satuan_harga' => 'per meter persegi',
                'whatsapp' => '081132109876',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 0, 'kamar_mandi' => 0,
                'luas_tanah' => 2000, 'luas_bangunan' => 0,
                'sertifikat' => 'SHM', 'daya_listrik' => 0,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 0,
                'kondisi_perabotan' => 'Tidak Ada', 'hadap' => 'Barat',
                'sumber_air' => 'Tidak Ada', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2433291099/display_1500/stock-photo--d-rendering-of-a-modern-luxurious-house-with-swimming-pool-2433291099.jpg', // Pemandangan Pantai
                    'https://www.shutterstock.com/shutterstock/photos/2442836131/display_1500/stock-photo--d-rendering-of-a-modern-luxurious-house-with-pool-2442836131.jpg', // Tanah Kosong
                    'https://www.shutterstock.com/shutterstock/photos/2434162451/display_1500/stock-photo--d-rendering-of-a-modern-luxurious-house-with-swimming-pool-2434162451.jpg', // Tanah Kosong
                ]),
            ],
        
            
            // KATEGORI 3: APARTEMEN (ID: 3) - 3 ENTRI
            [
                'agent_id' => 4,
                'kategori_id' => 3,
                'title' => 'Apartemen Studio Full Furnished Cihampelas, Bandung (Sewa)',
                'deskripsi' => 'Apartemen dengan fasilitas lengkap (kolam renang, gym) di lokasi strategis Dago-Cihampelas. Cocok untuk mahasiswa atau pekerja.',
                'alamat' => 'Jl. Dago No. 25 Tower B',
                'kabupaten_kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'harga' => 4500000,
                'satuan_harga' => 'per bulan',
                'whatsapp' => '082234567890',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 1, 'kamar_mandi' => 1,
                'luas_tanah' => 0, 'luas_bangunan' => 35,
                'sertifikat' => null, 'daya_listrik' => 2200,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Full Furnished', 'hadap' => 'Selatan',
                'sumber_air' => 'PDAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2279518887/display_1500/stock-photo--d-exterior-render-of-blocks-apartment-building-with-wood-and-plant-detail-in-facade-2279518887.jpg', // Studio
                    'https://www.shutterstock.com/shutterstock/photos/2279518883/display_1500/stock-photo--d-exterior-render-of-blocks-apartment-building-with-wood-and-plant-detail-in-facade-2279518883.jpg', // Balkon
                    'https://www.shutterstock.com/shutterstock/photos/2279518885/display_1500/stock-photo--d-exterior-render-of-blocks-apartment-building-with-wood-and-plant-detail-in-facade-2279518885.jpg', // Balkon
                ]),
            ],
            [
                'agent_id' => 2,
                'kategori_id' => 3,
                'title' => 'Apartemen View Kota 2BR di Pusat Surabaya',
                'deskripsi' => 'Cocok untuk investasi atau hunian, dekat Tunjungan Plaza.',
                'alamat' => 'Jl. Tunjungan No. 110',
                'kabupaten_kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'harga' => 950000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '087876543210',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 2, 'kamar_mandi' => 1,
                'luas_tanah' => 0, 'luas_bangunan' => 70,
                'sertifikat' => 'Strata Title', 'daya_listrik' => 3500,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Full Furnished', 'hadap' => 'Timur Laut',
                'sumber_air' => 'PDAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2279508979/display_1500/stock-photo-night-exterior-d-render-of-blocks-apartment-building-with-wood-and-plant-detail-in-facade-2279508979.jpg', // Ruang Tengah
                    'https://www.shutterstock.com/shutterstock/photos/2279440331/display_1500/stock-photo--d-exterior-render-of-apartment-building-facade-white-and-grey-facade-colour-glass-balcony-2279440331.jpg', // Pemandangan Kota
                    'https://www.shutterstock.com/shutterstock/photos/2279508979/display_1500/stock-photo-night-exterior-d-render-of-blocks-apartment-building-with-wood-and-plant-detail-in-facade-2279508979.jpg', // Pemandangan Kota
                ]),
            ],
            [
                'agent_id' => 1,
                'kategori_id' => 3,
                'title' => 'Apartemen 1BR View Gunung di Setiabudi (Sewa)',
                'deskripsi' => 'Pemandangan indah, udara sejuk. Full furnished siap huni.',
                'alamat' => 'Jl. Setiabudi No. 160 Tower C',
                'kabupaten_kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'harga' => 3500000,
                'satuan_harga' => 'per bulan',
                'whatsapp' => '085674532109',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 1, 'kamar_mandi' => 1,
                'luas_tanah' => 0, 'luas_bangunan' => 45,
                'sertifikat' => null, 'daya_listrik' => 2200,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Full Furnished', 'hadap' => 'Utara',
                'sumber_air' => 'PDAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/767187184/display_1500/stock-photo--d-render-of-building-exterior-767187184.jpg', // Kamar Modern
                    'https://www.shutterstock.com/shutterstock/photos/767187313/display_1500/stock-photo--d-render-of-building-exterior-767187313.jpg', // Kolam Renang Apartemen
                    'https://www.shutterstock.com/shutterstock/photos/767187184/display_1500/stock-photo--d-render-of-building-exterior-767187184.jpg', // Kolam Renang Apartemen
                ]),
            ],
        
            
            // KATEGORI 4: RUKO (ID: 4) - 3 ENTRI
            [
                'agent_id' => 1,
                'kategori_id' => 4,
                'title' => 'Ruko Strategis 3 Lantai di Pusat Kota Medan',
                'deskripsi' => 'Lokasi emas, cocok untuk usaha atau perkantoran. Akses mudah ke jalan utama.',
                'alamat' => 'Jl. Sudirman No. 55',
                'kabupaten_kota' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'harga' => 3800000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '087789012345',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 0, 'kamar_mandi' => 3,
                'luas_tanah' => 100, 'luas_bangunan' => 280,
                'sertifikat' => 'HGB', 'daya_listrik' => 7700,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 3,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Utara',
                'sumber_air' => 'PAM', 'hook' => 'Ya',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2675365159/display_1500/stock-photo--d-rendering-of-modern-minimalist-shophouse-exterior-design-2675365159.jpg', // Gedung Ruko
                    'https://www.shutterstock.com/shutterstock/photos/763289143/display_1500/stock-photo-shop-in-the-old-house-d-rendering-763289143.jpg', // Jalan depan Ruko
                    'https://www.shutterstock.com/shutterstock/photos/2064889412/display_1500/stock-photo--d-rendering-of-a-storefront-with-empty-signboards-2064889412.jpg', // Jalan depan Ruko
                ]),
            ],
            [
                'agent_id' => 2,
                'kategori_id' => 4,
                'title' => 'Ruko 2 Lantai Dekat Kampus, Makassar (Sewa)',
                'deskripsi' => 'Cocok untuk minimarket atau kafe, ramai mahasiswa. Area parkir luas.',
                'alamat' => 'Jl. Ahmad Yani No. 90',
                'kabupaten_kota' => 'Makassar',
                'provinsi' => 'Sulawesi Selatan',
                'harga' => 150000000,
                'satuan_harga' => 'per tahun',
                'whatsapp' => '083432109876',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 0, 'kamar_mandi' => 2,
                'luas_tanah' => 80, 'luas_bangunan' => 140,
                'sertifikat' => 'HGB', 'daya_listrik' => 5500,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 2,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Selatan',
                'sumber_air' => 'PAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2487188911/display_1500/stock-photo-modern-style-cottage-tiny-house-on-green-lawn-d-render-there-is-a-road-in-front-surrounded-by-2487188911.jpg', // Ruko 2 Lantai
                    'https://www.shutterstock.com/shutterstock/photos/1804316671/display_1500/stock-photo--d-render-exterior-of-home-landscape-north-america-1804316671.jpg', // Interior Kosong
                    'https://www.shutterstock.com/shutterstock/photos/2482794581/display_1500/stock-photo-modern-style-cottage-tiny-house-with-green-garden-d-render-there-is-a-road-in-front-surrounded-by-2482794581.jpg', // Interior Kosong
                ]),
            ],
            [
                'agent_id' => 3,
                'kategori_id' => 4,
                'title' => 'Ruko Baru 3 Lantai di Area Industri Batam',
                'deskripsi' => 'Dekat pelabuhan dan kawasan industri, cocok untuk kantor cabang.',
                'alamat' => 'Jl. Kartini No. 120',
                'kabupaten_kota' => 'Batam',
                'provinsi' => 'Kepulauan Riau',
                'harga' => 2100000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '089098765432',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 0, 'kamar_mandi' => 3,
                'luas_tanah' => 90, 'luas_bangunan' => 250,
                'sertifikat' => 'HGB', 'daya_listrik' => 7700,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 3,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Selatan',
                'sumber_air' => 'PAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2199977909/display_1500/stock-photo-a-contemporary-artwork-of-landscape-modern-design-of-exterior-d-illustration-of-outdoor-luxury-2199977909.jpg', // Ruko Modern
                    'https://www.shutterstock.com/shutterstock/photos/2199977815/display_1500/stock-photo-a-contemporary-artwork-of-landscape-modern-design-of-exterior-d-illustration-of-outdoor-luxury-2199977815.jpg', // Pintu Masuk
                    'https://www.shutterstock.com/shutterstock/photos/2373213431/display_1500/stock-photo--d-modeling-and-rendering-of-luxury-backyard-design-2373213431.jpg', // Pintu Masuk
                ]),
            ],
            
            // KATEGORI 5: PERKANTORAN (ID: 5) - 2 ENTRI
            [
                'agent_id' => 6,
                'kategori_id' => 5,
                'title' => 'Ruang Kantor Premium Grade A Kuningan (Sewa)',
                'deskripsi' => 'Ruang kantor siap pakai di gedung bergengsi. Dekat pusat bisnis Jakarta.',
                'alamat' => 'Jl. HR Rasuna Said Kav. 60',
                'kabupaten_kota' => 'Jakarta Selatan',
                'provinsi' => 'DKI Jakarta',
                'harga' => 500000000,
                'satuan_harga' => 'per tahun',
                'whatsapp' => '089901234567',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 0, 'kamar_mandi' => 0,
                'luas_tanah' => 0, 'luas_bangunan' => 150,
                'sertifikat' => null, 'daya_listrik' => 15000,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Barat Daya',
                'sumber_air' => 'Gedung', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://picsum.photos/id/300/800/600', // Ruang Kantor
                    'https://picsum.photos/id/301/800/600', // Gedung
                ]),
            ],
            [
                'agent_id' => 18,
                'kategori_id' => 5,
                'title' => 'Gedung Kantor Minimalis 2 Lantai di Padang (Sewa)',
                'deskripsi' => 'Lokasi strategis di pusat kota. Area parkir memadai. Siap pakai.',
                'alamat' => 'Jl. Sutan Syahrir No. 180',
                'kabupaten_kota' => 'Padang',
                'provinsi' => 'Sumatera Barat',
                'harga' => 120000000,
                'satuan_harga' => 'per tahun',
                'whatsapp' => '089018976543',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 0, 'kamar_mandi' => 4,
                'luas_tanah' => 250, 'luas_bangunan' => 350,
                'sertifikat' => 'HGB', 'daya_listrik' => 10000,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 2,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Timur',
                'sumber_air' => 'PAM', 'hook' => 'Ya',
                'foto_gallery' => json_encode([
                    'https://picsum.photos/id/302/800/600', // Kantor Modern
                    'https://picsum.photos/id/303/800/600', // Meja Rapat
                ]),
            ],
            
            // KATEGORI 6-10 (Gudang, Ruang Usaha, Pabrik, Hotel, Kost) - 1 ENTRI MASING-MASING
            [
                'agent_id' => 14, // Gudang
                'kategori_id' => 6,
                'title' => 'Gudang Logistik Luas Dekat Pelabuhan (Sewa)',
                'deskripsi' => 'Gudang baru dengan akses kontainer, area bongkar muat luas.',
                'alamat' => 'Jl. Raya Industri No. 50',
                'kabupaten_kota' => 'Bekasi',
                'provinsi' => 'Jawa Barat',
                'harga' => 700000000,
                'satuan_harga' => 'per tahun',
                'whatsapp' => '081211122233',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 0, 'kamar_mandi' => 2,
                'luas_tanah' => 1000, 'luas_bangunan' => 800,
                'sertifikat' => 'HGB', 'daya_listrik' => 20000,
                'kamar_tidur_pembantu' => 0, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Utara',
                'sumber_air' => 'Sumur Bor', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://picsum.photos/id/400/800/600', // Gudang
                    'https://picsum.photos/id/401/800/600', // Pintu Gudang
                ]),
            ],
            [
                'agent_id' => 1, // Ruang Usaha
                'kategori_id' => 7,
                'title' => 'Ruang Usaha Strategis di Mall Jakarta Pusat (Sewa)',
                'deskripsi' => 'Kios di lantai dasar mall ramai, cocok untuk retail atau kuliner.',
                'alamat' => 'Mall Thamrin City Lantai Dasar No. 10',
                'kabupaten_kota' => 'Jakarta Pusat',
                'provinsi' => 'DKI Jakarta',
                'harga' => 15000000,
                'satuan_harga' => 'per bulan',
                'whatsapp' => '081123456789',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 0, 'kamar_mandi' => 0,
                'luas_tanah' => 0, 'luas_bangunan' => 40,
                'sertifikat' => null, 'daya_listrik' => 5500,
                'kamar_tidur_pembantu' => null, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Timur',
                'sumber_air' => 'Gedung', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://picsum.photos/id/500/800/600', // Ruang Usaha
                    'https://picsum.photos/id/501/800/600', // Kios
                ]),
            ],
            [
                'agent_id' => 19, // Pabrik
                'kategori_id' => 8,
                'title' => 'Pabrik Siap Pakai di Kawasan Industri Cikarang (Jual)',
                'deskripsi' => 'Dilengkapi kantor dan mess karyawan, akses tol mudah.',
                'alamat' => 'Kawasan Industri Cikarang Blok A No. 1',
                'kabupaten_kota' => 'Bekasi',
                'provinsi' => 'Jawa Barat',
                'harga' => 25000000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '081132109876',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 0, 'kamar_mandi' => 6,
                'luas_tanah' => 5000, 'luas_bangunan' => 3500,
                'sertifikat' => 'HGB', 'daya_listrik' => 100000,
                'kamar_tidur_pembantu' => 0, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Kosong', 'hadap' => 'Selatan',
                'sumber_air' => 'WTP', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://picsum.photos/id/600/800/600', // Pabrik
                    'https://picsum.photos/id/601/800/600', // Produksi
                ]),
            ],
            [
                'agent_id' => 3, // Hotel
                'kategori_id' => 9,
                'title' => 'Hotel Bintang 3 Aktif di Pusat Kota Palu (Jual)',
                'deskripsi' => 'Terdiri dari 50 kamar, dilengkapi fasilitas meeting dan kolam renang.',
                'alamat' => 'Jl. Pemuda No. 200',
                'kabupaten_kota' => 'Palu',
                'provinsi' => 'Sulawesi Tengah',
                'harga' => 15000000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '082243210987',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 50, 'kamar_mandi' => 50,
                'luas_tanah' => 1500, 'luas_bangunan' => 4000,
                'sertifikat' => 'SHM', 'daya_listrik' => 80000,
                'kamar_tidur_pembantu' => 10, 'jumlah_lantai' => 5,
                'kondisi_perabotan' => 'Full Furnished', 'hadap' => 'Timur',
                'sumber_air' => 'PDAM', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://www.shutterstock.com/shutterstock/photos/2493599005/display_1500/stock-photo-the-facade-of-a-hotel-in-a-coastal-area-2493599005.jpg', // Hotel
                    'https://www.shutterstock.com/shutterstock/photos/2326632311/display_1500/stock-photo-modern-residential-complex-d-render-2326632311.jpg', // Hotel
                    'https://www.shutterstock.com/shutterstock/photos/2421977719/display_1500/stock-photo-samana-skyros-display-images-dubai-2421977719.jpg', // Kolam Hotel
                ]),
            ],
            [
                'agent_id' => 18, // Kost
                'kategori_id' => 10,
                'title' => 'Rumah Kost 20 Kamar Dekat Kampus Jakarta Barat (Jual)',
                'deskripsi' => 'Pendapatan pasif stabil, lokasi strategis di belakang kampus ternama.',
                'alamat' => 'Jl. Kebon Jeruk III No. 5',
                'kabupaten_kota' => 'Jakarta Barat',
                'provinsi' => 'DKI Jakarta',
                'harga' => 4000000000,
                'satuan_harga' => 'per unit',
                'whatsapp' => '089018976543',
                'tersedia' => true,
                'tipe' => 'jual',
                'kamar_tidur' => 20, 'kamar_mandi' => 20,
                'luas_tanah' => 300, 'luas_bangunan' => 450,
                'sertifikat' => 'SHM', 'daya_listrik' => 15000,
                'kamar_tidur_pembantu' => 1, 'jumlah_lantai' => 3,
                'kondisi_perabotan' => 'Semi Furnished', 'hadap' => 'Utara',
                'sumber_air' => 'Sumur Bor', 'hook' => 'Tidak',
                'foto_gallery' => json_encode([
                    'https://picsum.photos/id/800/800/600', // Bangunan Kost
                    'https://picsum.photos/id/801/800/600', // Kamar Kost
                ]),
            ],
            
            // KATEGORI 11: VILLA (ID: 11) - 1 ENTRI
            [
                'agent_id' => 3,
                'kategori_id' => 11,
                'title' => 'Villa Eksotis Kolam Renang Pribadi di Ubud, Bali (Sewa Harian)',
                'deskripsi' => 'Villa dengan pemandangan sawah yang menenangkan dan kolam renang pribadi. Ideal untuk liburan/honeymoon.',
                'alamat' => 'Jl. Raya Ubud No. 5',
                'kabupaten_kota' => 'Gianyar',
                'provinsi' => 'Bali',
                'harga' => 1800000,
                'satuan_harga' => 'per malam',
                'whatsapp' => '083876543210',
                'tersedia' => true,
                'tipe' => 'sewa',
                'kamar_tidur' => 3, 'kamar_mandi' => 3,
                'luas_tanah' => 450, 'luas_bangunan' => 280,
                'sertifikat' => 'SHM', 'daya_listrik' => 5500,
                'kamar_tidur_pembantu' => 1, 'jumlah_lantai' => 1,
                'kondisi_perabotan' => 'Full Furnished', 'hadap' => 'Utara',
                'sumber_air' => 'Sumur Bor', 'hook' => 'Ya',
                'foto_gallery' => json_encode([
                    'https://picsum.photos/id/900/800/600', // Villa
                    'https://picsum.photos/id/901/800/600', // Kolam Renang Villa
                ]),
            ],
        ];

        DB::table('properties')->insert($properties);
    }
}
